USE [master]
GO
/****** Object:  Database [TransportPaketa]    Script Date: 7.7.2024. 21:42:30 ******/
CREATE DATABASE [TransportPaketa]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TransportPaketa', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER01\MSSQL\DATA\TransportPaketa.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TransportPaketa_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER01\MSSQL\DATA\TransportPaketa_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [TransportPaketa] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TransportPaketa].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TransportPaketa] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TransportPaketa] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TransportPaketa] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TransportPaketa] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TransportPaketa] SET ARITHABORT OFF 
GO
ALTER DATABASE [TransportPaketa] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TransportPaketa] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TransportPaketa] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TransportPaketa] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TransportPaketa] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TransportPaketa] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TransportPaketa] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TransportPaketa] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TransportPaketa] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TransportPaketa] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TransportPaketa] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TransportPaketa] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TransportPaketa] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TransportPaketa] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TransportPaketa] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TransportPaketa] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TransportPaketa] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TransportPaketa] SET RECOVERY FULL 
GO
ALTER DATABASE [TransportPaketa] SET  MULTI_USER 
GO
ALTER DATABASE [TransportPaketa] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TransportPaketa] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TransportPaketa] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TransportPaketa] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TransportPaketa] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TransportPaketa] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'TransportPaketa', N'ON'
GO
ALTER DATABASE [TransportPaketa] SET QUERY_STORE = ON
GO
ALTER DATABASE [TransportPaketa] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [TransportPaketa]
GO
/****** Object:  Table [dbo].[Administrator]    Script Date: 7.7.2024. 21:42:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Administrator](
	[KorIme] [varchar](100) NOT NULL,
 CONSTRAINT [XPKAdministrator] PRIMARY KEY CLUSTERED 
(
	[KorIme] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Grad]    Script Date: 7.7.2024. 21:42:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Grad](
	[IdG] [int] IDENTITY(1,1) NOT NULL,
	[Naziv] [varchar](100) NOT NULL,
	[PostanskiBr] [varchar](100) NOT NULL,
 CONSTRAINT [XPKGrad] PRIMARY KEY CLUSTERED 
(
	[IdG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [XAK1Grad] UNIQUE NONCLUSTERED 
(
	[Naziv] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [XAK2Grad] UNIQUE NONCLUSTERED 
(
	[PostanskiBr] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Korisnik]    Script Date: 7.7.2024. 21:42:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Korisnik](
	[Ime] [varchar](100) NOT NULL,
	[Prezime] [varchar](100) NOT NULL,
	[KorIme] [varchar](100) NOT NULL,
	[Sifra] [varchar](100) NOT NULL,
	[BrPoslatihPaketa] [int] NOT NULL,
 CONSTRAINT [XPKKorisnik] PRIMARY KEY CLUSTERED 
(
	[KorIme] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Kurir]    Script Date: 7.7.2024. 21:42:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Kurir](
	[BrIsporucenihPaketa] [int] NOT NULL,
	[Profit] [decimal](10, 3) NOT NULL,
	[Status] [int] NOT NULL,
	[KorIme] [varchar](100) NOT NULL,
	[RegBr] [varchar](100) NOT NULL,
 CONSTRAINT [XPKKurir] PRIMARY KEY CLUSTERED 
(
	[KorIme] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Opstina]    Script Date: 7.7.2024. 21:42:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Opstina](
	[IdO] [int] IDENTITY(1,1) NOT NULL,
	[Xkoord] [int] NOT NULL,
	[Ykoord] [int] NOT NULL,
	[IdG] [int] NOT NULL,
	[Naziv] [varchar](100) NOT NULL,
 CONSTRAINT [XPKOpstina] PRIMARY KEY CLUSTERED 
(
	[IdO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [XAK1Opstina] UNIQUE NONCLUSTERED 
(
	[Naziv] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Paket]    Script Date: 7.7.2024. 21:42:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Paket](
	[IdP] [int] IDENTITY(1,1) NOT NULL,
	[Status] [int] NULL,
	[Cena] [decimal](10, 3) NULL,
	[VremePrihv] [datetime] NULL,
	[IdVoznje] [int] NULL,
	[IdZP] [int] NULL,
	[KorIme] [varchar](100) NULL,
	[Distanca] [decimal](10, 3) NULL,
 CONSTRAINT [XPKPaket] PRIMARY KEY CLUSTERED 
(
	[IdP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Ponuda]    Script Date: 7.7.2024. 21:42:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ponuda](
	[ProcenatCene] [int] NOT NULL,
	[IdZP] [int] NOT NULL,
	[KorIme] [varchar](100) NOT NULL,
	[IdPon] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [XPKPonuda] PRIMARY KEY CLUSTERED 
(
	[IdPon] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Vozilo]    Script Date: 7.7.2024. 21:42:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Vozilo](
	[RegBr] [varchar](100) NOT NULL,
	[TipGoriva] [int] NOT NULL,
	[Potrosnja] [decimal](10, 3) NOT NULL,
 CONSTRAINT [XPKVozilo] PRIMARY KEY CLUSTERED 
(
	[RegBr] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Voznja]    Script Date: 7.7.2024. 21:42:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Voznja](
	[VremePoc] [datetime] NOT NULL,
	[IdVoznje] [int] IDENTITY(1,1) NOT NULL,
	[KorIme] [varchar](100) NOT NULL,
	[Suma] [decimal](10, 3) NULL,
	[Potrosnja] [decimal](10, 3) NULL,
 CONSTRAINT [XPKVoznja] PRIMARY KEY CLUSTERED 
(
	[IdVoznje] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ZahtevKurir]    Script Date: 7.7.2024. 21:42:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ZahtevKurir](
	[KorIme] [varchar](100) NOT NULL,
	[RegBr] [varchar](100) NOT NULL,
 CONSTRAINT [XPKZahtevKurir] PRIMARY KEY CLUSTERED 
(
	[KorIme] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ZahtevPrevoz]    Script Date: 7.7.2024. 21:42:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ZahtevPrevoz](
	[IdZP] [int] IDENTITY(1,1) NOT NULL,
	[TipPaketa] [int] NOT NULL,
	[TezinaPaketa] [decimal](10, 3) NOT NULL,
	[IdOPre] [int] NOT NULL,
	[IdODos] [int] NOT NULL,
	[KorIme] [varchar](100) NOT NULL,
 CONSTRAINT [XPKZahtevPrevoz] PRIMARY KEY CLUSTERED 
(
	[IdZP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Korisnik] ADD  CONSTRAINT [Nula_1744847140]  DEFAULT ((0)) FOR [BrPoslatihPaketa]
GO
ALTER TABLE [dbo].[Kurir] ADD  CONSTRAINT [Nula_909186377]  DEFAULT ((0)) FOR [BrIsporucenihPaketa]
GO
ALTER TABLE [dbo].[Kurir] ADD  CONSTRAINT [Nula_664378298]  DEFAULT ((0)) FOR [Profit]
GO
ALTER TABLE [dbo].[Kurir] ADD  CONSTRAINT [Nula_430418619]  DEFAULT ((0)) FOR [Status]
GO
ALTER TABLE [dbo].[Paket] ADD  CONSTRAINT [Nula_213499770]  DEFAULT ((0)) FOR [Cena]
GO
ALTER TABLE [dbo].[Vozilo] ADD  CONSTRAINT [Nula_1692719108]  DEFAULT ((0)) FOR [Potrosnja]
GO
ALTER TABLE [dbo].[Administrator]  WITH CHECK ADD  CONSTRAINT [R_2] FOREIGN KEY([KorIme])
REFERENCES [dbo].[Korisnik] ([KorIme])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Administrator] CHECK CONSTRAINT [R_2]
GO
ALTER TABLE [dbo].[Kurir]  WITH CHECK ADD  CONSTRAINT [R_3] FOREIGN KEY([KorIme])
REFERENCES [dbo].[Korisnik] ([KorIme])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Kurir] CHECK CONSTRAINT [R_3]
GO
ALTER TABLE [dbo].[Kurir]  WITH CHECK ADD  CONSTRAINT [R_4] FOREIGN KEY([RegBr])
REFERENCES [dbo].[Vozilo] ([RegBr])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Kurir] CHECK CONSTRAINT [R_4]
GO
ALTER TABLE [dbo].[Opstina]  WITH CHECK ADD  CONSTRAINT [R_1] FOREIGN KEY([IdG])
REFERENCES [dbo].[Grad] ([IdG])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Opstina] CHECK CONSTRAINT [R_1]
GO
ALTER TABLE [dbo].[Paket]  WITH CHECK ADD  CONSTRAINT [R_14] FOREIGN KEY([KorIme])
REFERENCES [dbo].[Kurir] ([KorIme])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Paket] CHECK CONSTRAINT [R_14]
GO
ALTER TABLE [dbo].[Paket]  WITH CHECK ADD  CONSTRAINT [R_22] FOREIGN KEY([IdVoznje])
REFERENCES [dbo].[Voznja] ([IdVoznje])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Paket] CHECK CONSTRAINT [R_22]
GO
ALTER TABLE [dbo].[Paket]  WITH CHECK ADD  CONSTRAINT [R_23] FOREIGN KEY([IdZP])
REFERENCES [dbo].[ZahtevPrevoz] ([IdZP])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Paket] CHECK CONSTRAINT [R_23]
GO
ALTER TABLE [dbo].[Ponuda]  WITH CHECK ADD  CONSTRAINT [R_12] FOREIGN KEY([IdZP])
REFERENCES [dbo].[ZahtevPrevoz] ([IdZP])
GO
ALTER TABLE [dbo].[Ponuda] CHECK CONSTRAINT [R_12]
GO
ALTER TABLE [dbo].[Ponuda]  WITH CHECK ADD  CONSTRAINT [R_8] FOREIGN KEY([KorIme])
REFERENCES [dbo].[Kurir] ([KorIme])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Ponuda] CHECK CONSTRAINT [R_8]
GO
ALTER TABLE [dbo].[ZahtevKurir]  WITH CHECK ADD  CONSTRAINT [R_18] FOREIGN KEY([KorIme])
REFERENCES [dbo].[Korisnik] ([KorIme])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[ZahtevKurir] CHECK CONSTRAINT [R_18]
GO
ALTER TABLE [dbo].[ZahtevKurir]  WITH CHECK ADD  CONSTRAINT [R_19] FOREIGN KEY([RegBr])
REFERENCES [dbo].[Vozilo] ([RegBr])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ZahtevKurir] CHECK CONSTRAINT [R_19]
GO
ALTER TABLE [dbo].[ZahtevPrevoz]  WITH CHECK ADD  CONSTRAINT [R_6] FOREIGN KEY([IdOPre])
REFERENCES [dbo].[Opstina] ([IdO])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[ZahtevPrevoz] CHECK CONSTRAINT [R_6]
GO
ALTER TABLE [dbo].[Kurir]  WITH CHECK ADD  CONSTRAINT [Status0_1_433073605] CHECK  (([Status]=(0) OR [Status]=(1)))
GO
ALTER TABLE [dbo].[Kurir] CHECK CONSTRAINT [Status0_1_433073605]
GO
ALTER TABLE [dbo].[Paket]  WITH CHECK ADD  CONSTRAINT [Status0_1_2_3_2146338292] CHECK  (([Status]=(0) OR [Status]=(1) OR [Status]=(2) OR [Status]=(3)))
GO
ALTER TABLE [dbo].[Paket] CHECK CONSTRAINT [Status0_1_2_3_2146338292]
GO
ALTER TABLE [dbo].[Vozilo]  WITH CHECK ADD  CONSTRAINT [TipGoriva_2021023082] CHECK  (([TipGoriva]=(0) OR [TipGoriva]=(1) OR [TipGoriva]=(2)))
GO
ALTER TABLE [dbo].[Vozilo] CHECK CONSTRAINT [TipGoriva_2021023082]
GO
/****** Object:  StoredProcedure [dbo].[GrantCourierRequest]    Script Date: 7.7.2024. 21:42:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GrantCourierRequest]
    @Username NVARCHAR(100)
AS
BEGIN

    DECLARE @IdKor VARCHAR(100), @IdVoz VARCHAR(100);

    SELECT @IdKor = k.KorIme, @IdVoz = zk.RegBr
    FROM Korisnik k
    JOIN ZahtevKurir zk ON k.KorIme = zk.KorIme
    WHERE k.KorIme = @Username;

    IF @IdKor IS NULL OR @IdVoz IS NULL
    BEGIN
        RAISERROR('Request does not exist for the given username.', 16, 1);
        RETURN;
    END


    IF EXISTS (SELECT 1 FROM Kurir WHERE RegBr = @IdVoz)
    BEGIN
        RAISERROR('Vehicle is already assigned to another courier.', 16, 1);
        RETURN;
    END
     
    INSERT INTO Kurir (KorIme, BrIsporucenihPaketa, Profit, Status, RegBr)
    VALUES (@IdKor, 0, 0, 0, @IdVoz);

    DELETE FROM ZahtevKurir WHERE KorIme = @IdKor AND RegBr = @IdVoz;
END

GO
USE [master]
GO
ALTER DATABASE [TransportPaketa] SET  READ_WRITE 
GO
